[tool.poetry]
name = "repl_python3_Kur0bot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.0.1"
youtube_dl = "^2021.6.6"
PyNaCl = "^1.4.0"
gtts = "^2.2.2"
google-auth-oauthlib = "^0.4.5"
google-api-python-client = "^2.18.0"
pet-pet-gif = "^1.0.1"
schedule = "^1.1.0"
Flask = "^2.0.1"
python-dateutil = "^2.8.2"
yt-dlp = "^2021.10.10"
mcrcon = "^0.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
